# builder image

FROM ubuntu:noble as base

SHELL ["/bin/bash", "-c"]

RUN apt-get update -q -y && apt-get upgrade -q -y
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends build-essential ca-certificates curl libjemalloc-dev liblz4-dev libsnappy-dev libzstd-dev libudev-dev git

# golang
ARG GO_VERSION=1.19.13

RUN curl -sL -o /tmp/go.tar.gz https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz && \
    rm -rf /usr/local/go && \
    tar -C /usr/local -xzf /tmp/go.tar.gz && \
    ln -sf /usr/local/go/bin/* /usr/local/bin/ && \
    rm /tmp/go.tar.gz

RUN apt autoremove && apt autoclean

ENTRYPOINT ["/bin/bash", "-c"]

# EOF
